"""Add UPI model

Revision ID: ea10db272c01
Revises: ccfc705c08b0
Create Date: 2025-09-29 10:00:36.871289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea10db272c01'
down_revision = 'ccfc705c08b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upi', schema=None) as batch_op:
        batch_op.alter_column('upi_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_upi_upi_id', ['upi_id'])  # Named constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upi', schema=None) as batch_op:
        batch_op.drop_constraint('uq_upi_upi_id', type_='unique')  # Match name
        batch_op.alter_column('upi_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
